# Generated by Django 4.2.1 on 2023-07-20 02:20

from django.db import migrations, models
import djangoGears_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGears_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', djangoGears_auth.models.DjangoGearsUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
